modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="randomlycute" #mandatory
version="0.1.0" #mandatory
displayName="RandomlyCute" #mandatory
credits="Speshal thanks to Harry Talks and vsco.mod.minecraft" #optional
authors= "DakotaNeco NecoNeco"
description='''This mod has a bunch of cute random things I had made '''

[[dependencies.randomlycute]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"